import type { AxisVector, Profile, Reference } from "../types";
import { AXIS_BY_ID } from "./axes";
import { buildTokens, type TokenSummary } from "./tokens";
import { buildPalette, vectorFromScores } from "./render";

function clause(axisValue: number, low: string, high: string): string | null {
  const a = Math.abs(axisValue);
  if (a < 18) return null;
  const adverb = a >= 72 ? "strongly " : a >= 45 ? "clearly " : "";
  return `${adverb}${axisValue > 0 ? high : low}`;
}

/** A short paragraph — the format Claude reads best. */
export function buildBriefText(profile: Profile, byId: Map<string, Reference>): string {
  const clauses = profile.axes
    .map((s) => ({
      mag: Math.abs(s.value),
      text: clause(s.value, AXIS_BY_ID[s.id].briefLow, AXIS_BY_ID[s.id].briefHigh),
    }))
    .filter((c): c is { mag: number; text: string } => c.text !== null)
    .sort((a, b) => b.mag - a.mag)
    .slice(0, 7)
    .map((c) => c.text);

  const name = (id: string) => byId.get(id)?.name ?? id;
  const emulate = profile.emulate.map(name).join(", ");
  const avoid = profile.avoid.map(name).join(", ");

  const lead =
    clauses.length > 0
      ? `This taste profile favors ${joinList(clauses)}.`
      : "This taste profile is broadly balanced across the design axes.";

  const parts = [lead];
  if (emulate) parts.push(`Lean into the spirit of: ${emulate}.`);
  if (avoid) parts.push(`Steer away from: ${avoid}.`);
  return parts.join(" ");
}

function joinList(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

function tokenTable(s: TokenSummary): string {
  const rows: [string, string][] = [
    ["color.background", s.background],
    ["color.surface", s.surface],
    ["color.text", s.text],
    ["color.primary", s.primary],
    ["color.accent", s.accent],
    ["radius.md", s.radius],
    ["spacing", s.spacing],
    ["font.heading", s.fontHeading],
    ["font.body", s.fontBody],
    ["border.width", s.borderWidth],
    ["shadow.md", s.shadow],
  ];
  return ["| Token | Value |", "| --- | --- |", ...rows.map(([k, v]) => `| \`${k}\` | ${v} |`)].join(
    "\n",
  );
}

/**
 * The Claude-facing artifact: a SKILL.md the way "Taste" (buildwithtaste.com)
 * ships one. Drop it into `.claude/skills/aesthetic-profile/SKILL.md` and Claude
 * Code reads it on relevant prompts.
 */
export function buildSkillMd(profile: Profile, byId: Map<string, Reference>): string {
  const { summary } = buildTokens(profile.axes);
  const brief = buildBriefText(profile, byId);

  // Order by conjoint importance (how much the axis actually drove choices),
  // not just by where the profile sits.
  const impById = new Map(profile.drivers.map((d) => [d.id, d.importance]));
  const principles = profile.axes
    .map((s) => ({ s, imp: impById.get(s.id) ?? 0 }))
    .filter(({ s, imp }) => imp >= 0.3 || Math.abs(s.value) >= 22)
    .sort((a, b) => b.imp - a.imp || Math.abs(b.s.value) - Math.abs(a.s.value))
    .map(({ s, imp }) => {
      const def = AXIS_BY_ID[s.id];
      const pole = s.value > 0 ? def.highPole : def.lowPole;
      const driver = imp >= 0.6 ? " — **key driver**" : "";
      const conf = s.confidence < 0.45 && imp < 0.6 ? " _(exploratory)_" : "";
      return `- **${def.label} → ${pole}** (${s.value > 0 ? "+" : ""}${s.value}): ${
        s.value > 0 ? def.briefHigh : def.briefLow
      }${driver}.${conf}`;
    })
    .join("\n");

  const refLine = (id: string) => {
    const r = byId.get(id);
    return r ? `- ${r.name} — _${r.family}_` : `- ${id}`;
  };

  const lowConf = profile.axes.filter((s) => s.confidence < 0.45).map((s) => AXIS_BY_ID[s.id].label);

  return `---
name: aesthetic-profile
description: Personal design taste profile for ${profile.meta.project}. Apply when generating, restyling, or reviewing any UI, landing page, component, or visual artifact for this project. Use these tokens and principles instead of generic defaults.
---

# Aesthetic Profile — ${profile.meta.project}

${brief}

## Design principles

${principles || "_No strong directional preferences detected — keep it balanced._"}

## Design tokens (W3C DTCG)

Colors are OKLCH (hex in parentheses). Prefer these over inventing new values.

${tokenTable(summary)}

## Emulate

${profile.emulate.map(refLine).join("\n") || "- (none)"}

## Avoid

${profile.avoid.map(refLine).join("\n") || "- (none)"}

## Provenance

Generated by ${profile.meta.generator} from **${profile.meta.comparisons} pairwise comparisons** across **${profile.meta.referenceCount} references** on ${profile.meta.createdAt.slice(0, 10)}.${
    lowConf.length
      ? ` Treat these axes as directional, not firm: ${lowConf.join(", ")}.`
      : ""
  }
`;
}

/** The single bundled artifact (axis scores + drivers + tokens + brief + ranking). */
export function buildBundleJson(profile: Profile, byId: Map<string, Reference>) {
  const { dtcg } = buildTokens(profile.axes);
  const ref = (id: string) => {
    const r = byId.get(id);
    return { id, name: r?.name ?? id, family: r?.family ?? "" };
  };
  return {
    $generator: profile.meta.generator,
    meta: profile.meta,
    consistency: profile.consistency,
    validation: profile.validation,
    brief: buildBriefText(profile, byId),
    axes: profile.axes.map((s) => ({
      id: s.id,
      label: AXIS_BY_ID[s.id].label,
      value: s.value,
      pole: s.value > 0 ? AXIS_BY_ID[s.id].highPole : AXIS_BY_ID[s.id].lowPole,
      confidence: s.confidence,
    })),
    drivers: profile.drivers.map((d) => ({
      id: d.id,
      label: AXIS_BY_ID[d.id].label,
      weight: d.weight,
      importance: d.importance,
      pole: d.weight > 0 ? AXIS_BY_ID[d.id].highPole : AXIS_BY_ID[d.id].lowPole,
    })),
    tokens: dtcg,
    emulate: profile.emulate.map(ref),
    avoid: profile.avoid.map(ref),
    ranking: profile.ranking.map((s) => ({ ...ref(s.id), bt: s.bt, elo: s.elo, comparisons: s.comparisons })),
  };
}

/** A ready-to-paste instruction block for Claude (prompt or project memory). */
export function buildClaudePrompt(profile: Profile, byId: Map<string, Reference>): string {
  const { summary } = buildTokens(profile.axes);
  const drivers = profile.drivers
    .filter((d) => d.importance >= 0.4)
    .slice(0, 6)
    .map((d) => {
      const def = AXIS_BY_ID[d.id];
      return `${def.label}→${d.weight > 0 ? def.highPole : def.lowPole}`;
    })
    .join(", ");
  const names = (ids: string[]) =>
    ids.map((i) => byId.get(i)?.name).filter(Boolean).join(", ");

  return `Apply this aesthetic profile to everything you design for "${profile.meta.project}" — layout, color, type, spacing — instead of generic defaults.

Feel: ${buildBriefText(profile, byId)}

Priority axes: ${drivers || "balanced across axes"}.

Tokens (OKLCH, hex in parens):
- background ${summary.background}
- surface ${summary.surface}
- text ${summary.text}
- primary ${summary.primary}
- accent ${summary.accent}
- radius ${summary.radius}; spacing ${summary.spacing}; border ${summary.borderWidth}
- headings ${summary.fontHeading}; body ${summary.fontBody}
- shadow ${summary.shadow}

Emulate the spirit of: ${names(profile.emulate) || "n/a"}.
Avoid: ${names(profile.avoid) || "n/a"}.
When in doubt, stay consistent with the feel above and prefer the priority axes.`;
}

/** CSS custom properties (:root) derived from the profile's tokens. */
export function buildCssVars(profile: Profile): string {
  const { style } = buildTokens(profile.axes);
  const p = style.palette;
  const sp = Math.max(4, style.gap);
  const lines = [
    `  --color-bg: ${p.bg.css};`,
    `  --color-surface: ${p.surface.css};`,
    `  --color-surface-alt: ${p.surfaceAlt.css};`,
    `  --color-text: ${p.text.css};`,
    `  --color-text-muted: ${p.textMuted.css};`,
    `  --color-border: ${p.border.css};`,
    `  --color-primary: ${p.primary.css};`,
    `  --color-primary-foreground: ${p.primaryFg.css};`,
    `  --color-accent: ${p.accent.css};`,
    `  --radius: ${style.radius}px;`,
    `  --space: ${sp}px;`,
    `  --border-width: ${style.borderWidth}px;`,
    `  --font-heading: ${style.headingFont};`,
    `  --font-body: ${style.bodyFont};`,
    `  --shadow: ${style.shadow};`,
  ];
  return `:root {\n${lines.join("\n")}\n}`;
}

/** A shadcn/ui theme (:root + .dark) mapping the profile onto shadcn's tokens. */
export function buildShadcnTheme(profile: Profile): string {
  const vec = vectorFromScores(profile.axes);
  const { style } = buildTokens(profile.axes);
  const light = buildPalette({ ...vec, tone: -55 } as AxisVector);
  const dark = buildPalette({ ...vec, tone: 60 } as AxisVector);
  const radius = `${Math.round((style.radius / 16) * 1000) / 1000}rem`;
  const block = (p: ReturnType<typeof buildPalette>) =>
    [
      ["--background", p.bg.css],
      ["--foreground", p.text.css],
      ["--card", p.surface.css],
      ["--card-foreground", p.text.css],
      ["--popover", p.surface.css],
      ["--popover-foreground", p.text.css],
      ["--primary", p.primary.css],
      ["--primary-foreground", p.primaryFg.css],
      ["--secondary", p.surfaceAlt.css],
      ["--secondary-foreground", p.text.css],
      ["--muted", p.surfaceAlt.css],
      ["--muted-foreground", p.textMuted.css],
      ["--accent", p.accent.css],
      ["--accent-foreground", p.primaryFg.css],
      ["--destructive", "oklch(0.62 0.21 25)"],
      ["--destructive-foreground", "oklch(0.99 0 0)"],
      ["--border", p.border.css],
      ["--input", p.border.css],
      ["--ring", p.primary.css],
    ]
      .map(([k, v]) => `    ${k}: ${v};`)
      .join("\n");
  return `/* shadcn/ui theme — generated from your taste profile (OKLCH) */
:root {
    --radius: ${radius};
${block(light)}
}

.dark {
${block(dark)}
}`;
}

/** A Tailwind theme.extend config derived from the profile (hex for v3 compat). */
export function buildTailwindTheme(profile: Profile): string {
  const { style } = buildTokens(profile.axes);
  const p = style.palette;
  const sp = Math.max(4, style.gap);
  const fam = (f: string) => JSON.stringify(f.split(",").map((s) => s.trim().replace(/^"|"$/g, "")));
  return `// tailwind.config.js — theme.extend (generated from your taste profile)
module.exports = {
  theme: {
    extend: {
      colors: {
        background: "${p.bg.hex}",
        surface: "${p.surface.hex}",
        foreground: "${p.text.hex}",
        muted: "${p.textMuted.hex}",
        border: "${p.border.hex}",
        primary: { DEFAULT: "${p.primary.hex}", foreground: "${p.primaryFg.hex}" },
        accent: "${p.accent.hex}",
      },
      borderRadius: { sm: "${Math.round(style.radius * 0.5)}px", DEFAULT: "${style.radius}px", lg: "${Math.round(style.radius * 1.6)}px" },
      fontFamily: { heading: ${fam(style.headingFont)}, body: ${fam(style.bodyFont)} },
      boxShadow: { sm: "${style.shadowSm}", DEFAULT: "${style.shadow}" },
      spacing: { xs: "${Math.round(sp * 0.5)}px", sm: "${sp}px", md: "${Math.round(sp * 1.8)}px", lg: "${Math.round(sp * 3)}px" },
    },
  },
};`;
}
