import type { Profile, Reference } from "../types";
import { AXIS_BY_ID } from "./axes";
import { buildTokens, type TokenSummary } from "./tokens";

function clause(axisValue: number, low: string, high: string): string | null {
  const a = Math.abs(axisValue);
  if (a < 18) return null;
  const adverb = a >= 72 ? "strongly " : a >= 45 ? "clearly " : "";
  return `${adverb}${axisValue > 0 ? high : low}`;
}

/** A short paragraph — the format Claude reads best. */
export function buildBriefText(profile: Profile, byId: Map<string, Reference>): string {
  const clauses = profile.axes
    .map((s) => ({
      mag: Math.abs(s.value),
      text: clause(s.value, AXIS_BY_ID[s.id].briefLow, AXIS_BY_ID[s.id].briefHigh),
    }))
    .filter((c): c is { mag: number; text: string } => c.text !== null)
    .sort((a, b) => b.mag - a.mag)
    .slice(0, 7)
    .map((c) => c.text);

  const name = (id: string) => byId.get(id)?.name ?? id;
  const emulate = profile.emulate.map(name).join(", ");
  const avoid = profile.avoid.map(name).join(", ");

  const lead =
    clauses.length > 0
      ? `This taste profile favors ${joinList(clauses)}.`
      : "This taste profile is broadly balanced across the design axes.";

  const parts = [lead];
  if (emulate) parts.push(`Lean into the spirit of: ${emulate}.`);
  if (avoid) parts.push(`Steer away from: ${avoid}.`);
  return parts.join(" ");
}

function joinList(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

function tokenTable(s: TokenSummary): string {
  const rows: [string, string][] = [
    ["color.background", s.background],
    ["color.surface", s.surface],
    ["color.text", s.text],
    ["color.primary", s.primary],
    ["color.accent", s.accent],
    ["radius.md", s.radius],
    ["spacing", s.spacing],
    ["font.heading", s.fontHeading],
    ["font.body", s.fontBody],
    ["border.width", s.borderWidth],
    ["shadow.md", s.shadow],
  ];
  return ["| Token | Value |", "| --- | --- |", ...rows.map(([k, v]) => `| \`${k}\` | ${v} |`)].join(
    "\n",
  );
}

/**
 * The Claude-facing artifact: a SKILL.md the way "Taste" (buildwithtaste.com)
 * ships one. Drop it into `.claude/skills/aesthetic-profile/SKILL.md` and Claude
 * Code reads it on relevant prompts.
 */
export function buildSkillMd(profile: Profile, byId: Map<string, Reference>): string {
  const { summary } = buildTokens(profile.axes);
  const brief = buildBriefText(profile, byId);

  const principles = profile.axes
    .filter((s) => Math.abs(s.value) >= 18)
    .sort((a, b) => Math.abs(b.value) - Math.abs(a.value))
    .map((s) => {
      const def = AXIS_BY_ID[s.id];
      const pole = s.value > 0 ? def.highPole : def.lowPole;
      const tag = s.confidence < 0.45 ? " _(exploratory)_" : "";
      return `- **${def.label} → ${pole}** (${s.value > 0 ? "+" : ""}${s.value}): ${
        s.value > 0 ? def.briefHigh : def.briefLow
      }.${tag}`;
    })
    .join("\n");

  const refLine = (id: string) => {
    const r = byId.get(id);
    return r ? `- ${r.name} — _${r.family}_` : `- ${id}`;
  };

  const lowConf = profile.axes.filter((s) => s.confidence < 0.45).map((s) => AXIS_BY_ID[s.id].label);

  return `---
name: aesthetic-profile
description: Personal design taste profile for ${profile.meta.project}. Apply when generating, restyling, or reviewing any UI, landing page, component, or visual artifact for this project. Use these tokens and principles instead of generic defaults.
---

# Aesthetic Profile — ${profile.meta.project}

${brief}

## Design principles

${principles || "_No strong directional preferences detected — keep it balanced._"}

## Design tokens (W3C DTCG)

Colors are OKLCH (hex in parentheses). Prefer these over inventing new values.

${tokenTable(summary)}

## Emulate

${profile.emulate.map(refLine).join("\n") || "- (none)"}

## Avoid

${profile.avoid.map(refLine).join("\n") || "- (none)"}

## Provenance

Generated by ${profile.meta.generator} from **${profile.meta.comparisons} pairwise comparisons** across **${profile.meta.referenceCount} references** on ${profile.meta.createdAt.slice(0, 10)}.${
    lowConf.length
      ? ` Treat these axes as directional, not firm: ${lowConf.join(", ")}.`
      : ""
  }
`;
}

/** The single bundled artifact (axis scores + tokens + brief + ranking). */
export function buildBundleJson(profile: Profile, byId: Map<string, Reference>) {
  const { dtcg } = buildTokens(profile.axes);
  const ref = (id: string) => {
    const r = byId.get(id);
    return { id, name: r?.name ?? id, family: r?.family ?? "" };
  };
  return {
    $generator: profile.meta.generator,
    meta: profile.meta,
    brief: buildBriefText(profile, byId),
    axes: profile.axes.map((s) => ({
      id: s.id,
      label: AXIS_BY_ID[s.id].label,
      value: s.value,
      pole: s.value > 0 ? AXIS_BY_ID[s.id].highPole : AXIS_BY_ID[s.id].lowPole,
      confidence: s.confidence,
    })),
    tokens: dtcg,
    emulate: profile.emulate.map(ref),
    avoid: profile.avoid.map(ref),
    ranking: profile.ranking.map((s) => ({ ...ref(s.id), bt: s.bt, elo: s.elo, comparisons: s.comparisons })),
  };
}
